language: python
python:
- '2.7'
before_install:
- sudo apt-get update
- sudo apt-get install libhdf5-serial-dev h5utils
- pip install Cython
- pip install numpy
- pip install h5py
- pip install PyXB
install:
- python setup.py build
script: python setup.py test
deploy:
  provider: pypi
  user: naegelejd
  on:
    tags: true
  password:
    secure: bxGtr0gxbYWWhVdXRB0j9BxebI4dpMhX16IpRdBFvCJ2fcN5UICDn5jFVsWZiFV5XcUpnS6uYo9XreN+nDXcatLfTIf8u8PkpuGj31ooSWjNc1PGAbPCFK+RdGadPnT8OeiIISwmn94UjRPjTBbrcW/5gdVKykJiFW2kr/JuPrQ=
